#!/bin/bash

# Description: Load testing use 4000 PUT requests from 4 cleints, using 3 urls that map to each of the partitions
cat putURLS | parallel './ab-graph.sh -E "-u put1.data" -c 1 -n 1000  -u "http://localhost:8080/?"{}'

