#!/bin/bash

# Usage ./addTarget dh2026pc05 8080
PROJECT_ROOT="`pwd`/../"

if [[ $# -ne 2 ]]; then 
    echo "Usage ./addTarget hostname portnum"
    exit 1
fi


ssh $1 "cd $PWD; ./startServiceLocal $2" 1> "/virtual/$USER/out/$1.out" 2> "/virtual/$USER/out/$1.err" &
(sleep 3; echo "ADD $1 $2" | nc -q 0 localhost 8081) 

echo "$1:$2" >> "$PROJECT_ROOT/config/allhosts"