#!/bin/bash

# Usage ./addTarget dh2026pc05 8080
PROJECT_ROOT="`pwd`/../"

if [[ $# -ne 2 ]]; then 
    echo "Usage ./addTarget hostname portnum"
    exit 1
fi

(sleep 1; echo "ADD $1 $2" | nc -q 0 localhost 8081) &
ssh $1 "cd $PROJECT_ROOT; java URLShortner $2" > /dev/null &


echo "$1:$2" >> ../config/allhosts