#!/bin/bash

# Close the url shortener service on all hosts
PROJECT_ROOT = "`pwd`/../"
cd $PROJECT_ROOT

for host in `cat config/allhosts`
do 
    readarray -d : -t info <<< $host
    echo "Killing URLShortener service on ${info[0]}:${info[1]}"
    ssh "${info[0]}" "fuser -k -TERM -n tcp ${info[1]}" 1> /dev/null 2> /dev/null
done

echo "STOP" | nc -q 0 localhost 8081