#!/bin/bash

# Usage ./rmTarget dh2026pc05 8080
PROJECT_ROOT="`pwd`/../";


if [[ $# -ne 2 ]]; then 
    echo "Usage ./rmTarget hostname portnum"
    exit 1
fi

ssh $1 "cd $PWD; ./stopServiceLocal" 1> /dev/null 2> /dev/null& 
echo "REMOVE $1 $2" | nc -q 0 localhost 8081

echo "$1:$2" >> "$PROJECT_ROOT/config/allhosts"
