#!/bin/bash

PROJECT_ROOT="`pwd`/../";

if [[ $# -ne 2 ]]; then 
    echo "Usage ./standbyTarget hostname portnum"
    exit 1
fi

ssh $1 "cd $PROJECT_ROOT/orchestration; ./startServiceLocal $2" 1> "/virtual/$USER/out/$1.out" 2> "/virtual/$USER/out/$1.err" &
(sleep 3; echo "STANDBY $1 $2" | nc -q 0 localhost 8081)

echo "$1:$2" >> "$PROJECT_ROOT/config/allhosts"
