#!/bin/bash

# usage ./startServiceLocal <portnum>
PROJECT_ROOT="`pwd`/../";

if [[ $# -ne 1 ]]; then 
    echo "Usage ./startServiceLocal portnum"
    exit 1
fi

# create the database
mkdir -p /virtual/$USER
rm /virtual/$USER/url-$(hostname).db*
sqlite3 /virtual/$USER/url-$(hostname).db < $PROJECT_ROOT/javaSQLite/schema.sql

cd $PROJECT_ROOT
java -classpath ".:javaSQLite/sqlite-jdbc-3.39.3.0.jar" URLShortner.java $1 jdbc:sqlite:/virtual/$USER/url-$(hostname).db


